### ISSUE TITLE
Voyager crashed

### ISSUE THREAD

**Issue by jbibla** [cosmos/voyager#1040]
UI Version: 0.9.1

Description: Voyager ran into an error full screen modal.

Not sure how to reproduce.
```
main-process: Node 178.128.14.40 is alive
main-process: Picked node: 178.128.14.40
main-process: starting gaia rest server with nodeIP 178.128.14.40:26657
main-process: startLCD /Users/jordan/.cosmos-voyager/gaia-7003/lcd
main-process: spawning /private/var/folders/mw/jjgtf89s2yqby0vqjd15x1d80000gn/T/AppTranslocation/49DA80D0-3FC2-4333-BED8-963B3220B792/d/Cosmos Voyager.app/Contents/Resources/app/bin/gaiacli with args ""advanced" "rest-server" "--laddr" "tcp://localhost:9071" "--home" "/Users/jordan/.cosmos-voyager/gaia-7003/lcd" "--node" "178.128.14.40:26657" "--chain-id" "gaia-7003""
main-process: gaiacli: I[07-28|23:21:15.312] Served RPC HTTP response                     module=rest-server method=GET url=/node_version status=200 duration=2687 remoteAddr=127.0.0.1:55830

main-process: gaiacli: I[07-28|23:21:15.316] Served RPC HTTP response                     module=rest-server method=GET url=/keys status=200 duration=0 remoteAddr=127.0.0.1:55872

main-process: gaia rest server ready
main-process: Signaling connected node
main-process: gaiacli: I[07-28|23:21:15.325] Served RPC HTTP response                     module=rest-server method=GET url=/keys status=200 duration=0 remoteAddr=127.0.0.1:55834

main-process: gaiacli: panic: resource temporarily unavailable

goroutine 1 [running]:
github.com/cosmos/cosmos-sdk/client/lcd.createHandler(0xc420808d20, 0x5, 0x7ffeefbffca4)
	/go/src/github.com/cosmos/cosmos-sdk/client/lcd/root.go:78 +
main-process: gaiacli: 0x612
github.com/cosmos/cosmos-sdk/client/lcd.ServeCommand.func1(0xc4208c98c0, 0xc42048b280, 0x0, 0x8, 0x0, 0x0)
	/go/src/github.com/cosmos/cosmos-sdk/client/lcd/root.go:
main-process: gaiacli: 40 +0x8e
github.com/cosmos/cosmos-sdk/vendor/github.com/spf13/cobra.(*Command).execute(0xc4208c98c0, 0xc42048b180, 0x8, 0x8, 0xc4208c98c0, 0xc42048b180)
	/go/src/github.com/cosmos/cosmos-sdk/vendor/github.com/spf13/cobra/command.go:698 +0x46d
github.com/cosmos/cosmos-sdk/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x209a520, 0x19ec3da, 
main-process: gaiacli: 0x24, 0xc4208e02d8)
	/go/src/github.com/cosmos/cosmos-sdk/vendor/github.com/spf13/cobra/command.go:783 +0x2e4
github.com/cosmos/cosmos-sdk/vendor/github.com/spf13/cobra.(*Command).Execute(0x209a520, 0xc4208c4940, 0x209a600)
	/go/src/github.com/cosmos/cosmos-sdk/vendor/github.com/spf13/cobra/command.go:736 +0x2b
github.com/cosmos/cosmos-sdk/vendor/github.com/tendermint/tendermint/libs/cli.Executor.Execute(
main-process: gaiacli: 0x209a520, 0x1b35ae0, 0x2, 0xc4208acc20)
	/go/src/github.com/cosmos/cosmos-sdk/vendor/github.com/tendermint/tendermint/libs/cli/setup.go:89 +0x4e
main.main()
	/go/src/github.com/cosmos/cosmos-sdk/cmd/gaia/cmd/gaiacli/main.go:146 +
main-process: gaiacli: 0xb88

main-process: gaiacli exited with code 2
main-process: The gaiacli rest-server (LCD) exited unplanned
main-process: gaiacli: I[07-28|23:21:15.594] Served RPC HTTP response                     module=rest-server method=GET url=/node_version status=200 duration=2969 remoteAddr=127.0.0.1:55829

main-process: Starting reconnect
main-process: Stopping the LCD server
main-process: Node 10.128.0.13 is down
main-process: pinging node: http://206.189.189.150:26657
main-process: gaiacli: I[07-28|23:21:17.312] Served RPC HTTP response                     module=rest-server method=GET url=/node_version status=200 duration=1988 remoteAddr=127.0.0.1:55874

main-process: Node 206.189.189.150 is down
main-process: pinging node: http://5.101.166.189:26657
main-process: Node 5.101.166.189 is down
main-process: pinging node: http://62.77.157.50:26657
main-process: Node 62.77.157.50 is alive
main-process: Picked node: 62.77.157.50
main-process: starting gaia rest server with nodeIP 62.77.157.50:26657
main-process: startLCD /Users/jordan/.cosmos-voyager/gaia-7003/lcd
main-process: spawning /private/var/folders/mw/jjgtf89s2yqby0vqjd15x1d80000gn/T/AppTranslocation/49DA80D0-3FC2-4333-BED8-963B3220B792/d/Cosmos Voyager.app/Contents/Resources/app/bin/gaiacli with args ""advanced" "rest-server" "--laddr" "tcp://localhost:9071" "--home" "/Users/jordan/.cosmos-voyager/gaia-7003/lcd" "--node" "62.77.157.50:26657" "--chain-id" "gaia-7003""
main-process: gaiacli: I[07-28|23:21:20.524] Served RPC HTTP response                     module=rest-server method=GET url=/keys status=200 duration=0 remoteAddr=127.0.0.1:55913

main-process: gaia rest server ready
main-process: Signaling connected node
main-process: gaiacli: I[07-28|23:21:20.543] Served RPC HTTP response                     module=rest-server method=GET url=/keys status=200 duration=0 remoteAddr=127.0.0.1:55834

main-process: gaiacli: panic: resource temporarily unavailable

goroutine 1 [running]:
github.com/cosmos/cosmos-sdk/client/lcd.createHandler(0xc4201375e0, 0x5, 0x7ffeefbffcac)
	/go/src/github.com/cosmos/cosmos-sdk/client/lcd/root.go:78 +0x612
github.com/cosmos/cosmos-sdk/client/lcd.ServeCommand.func1(0xc4200bfb00, 0xc420139080, 0x0, 0x8, 0x0, 0x0)
	/go/src/github.com/cosmos/cosmos-sdk/client/lcd/root.go:40 +0x8e
github.com/cosmos/cosmos-sdk/vendor/github.com/spf13/cobra.(*Command).execute(0xc4200bfb00, 0xc420138f80, 0x8, 0x8, 0xc4200bfb00, 0xc420138f80)
	/go/src/github.com/cosmos/cosmos-sdk/vendor/github.com/spf13/cobra/command.go:698 +0x46d
github.com/cosmos/cosmos-sdk/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x209a520, 0x19ec3da, 0x24, 0xc42084d878)
	/go/src/github.com/cosmos/cosmos-sdk/vendor/github.com/spf13/cobra/command.go:783 +0x2e4
github.com/cosmos/cosmos-sdk/vendor/github.com/spf13/cobra.(*Command).Execute(0x209a520, 0xc420890ca0, 0x209a600)
	/go/src/github.com/cosmos/cosmos-sdk/vendor/github.com/spf13/cobra/command.go:736 +0x2b
github.com/cosmos/cosmos-sdk/vendor/github.com/tendermint/tendermint/libs/cli.Executor.Execute(0x209a520, 0x1b35ae0, 0x2, 0xc4208867e0)
	/go/src/github.com/cosmos/cosmos-sdk/vendor/github.com/tendermint/tendermint/libs/cli/setup.go:89 +0x4e
main.main()
	/go/src/github.com/cosmos/cosmos-sdk/cmd/gaia/cmd/gaiacli/main.go:146 +0xb88

main-process: gaiacli exited with code 2
main-process: The gaiacli rest-server (LCD) exited unplanned
main-process: gaiacli: I[07-28|23:21:21.254] Served RPC HTTP response                     module=rest-server method=GET url=/node_version status=200 duration=727 remoteAddr=127.0.0.1:55914

main-process: Starting reconnect
main-process: Stopping the LCD server
main-process: gaiacli: I[07-28|23:40:16.263] Served RPC HTTP response                     module=rest-server method=GET url="/txs?tag=sender_bech32=%27cosmosaccaddr1qk2q3l28t6qhzyc7p832ep8uwd0ypstgqla8yx%27" status=200 duration=65 remoteAddr=127.0.0.1:60928
I[07-28|23:40:16.264] Served RPC HTTP response                     module=rest-server method=GET url=/accounts/cosmosaccaddr1qk2q3l28t6qhzyc7p832ep8uwd0ypstgqla8yx status=200 duration=66 remoteAddr=127.0.0.1:60927

main-process: gaiacli: I[07-28|23:40:16.352] Served RPC HTTP response                     module=rest-server method=GET url="/txs?tag=recipient_bech32=%27cosmosaccaddr1qk2q3l28t6qhzyc7p832ep8uwd0ypstgqla8yx%27" status=200 duration=153 remoteAddr=127.0.0.1:60930
```

**Comment by faboweb** [comment]
Dupe of #1023

**Comment by jbibla** [comment]
didn't happen in start - but i will close in favour of #1023
