### ISSUE TITLE
last step of build for darwin fails

### ISSUE THREAD

**Issue by jbibla** [cosmos/voyager#1127]
```
Downloading tmp-71-0-electron-v2.0.2-darwin-x64.zip
[============================================>] 100.0% of 48.64 MB (61.47 kB/s)
(node:71) UnhandledPromiseRejectionWarning: Error: Generated checksum for "electron-v2.0.2-darwin-x64.zip" did not match expected checksum.
    at Hash.hasher.on (/usr/src/app/node_modules/sumchecker/index.js:151:20)
    at Hash.emit (events.js:180:13)
    at emitReadable_ (_stream_readable.js:525:10)
    at emitReadable (_stream_readable.js:519:7)
    at addChunk (_stream_readable.js:285:7)
    at readableAddChunk (_stream_readable.js:261:11)
    at Hash.Readable.push (_stream_readable.js:218:10)
    at Hash.Transform.push (_stream_transform.js:146:32)
    at Hash._flush (internal/crypto/hash.js:43:8)
    at Hash.prefinish (_stream_transform.js:136:10)
    at Hash.emit (events.js:180:13)
    at prefinish (_stream_writable.js:625:14)
    at finishMaybe (_stream_writable.js:633:5)
    at endWritable (_stream_writable.js:644:3)
    at Hash.Writable.end (_stream_writable.js:586:5)
    at ReadStream.onend (_stream_readable.js:607:10)
(node:71) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 7)
(node:71) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

`finishMaybe` - 🤣

**Comment by fedekunze** [comment]
Probably missing a `try` and `catch (err)` somewhere

**Comment by faboweb** [comment]
`try catch` would just hide the error. Did you update the electron version?

**Comment by faboweb** [comment]
@jbibla could you check again today, maybe this was just a Monday thing?!

**Comment by jbibla** [comment]
apologies. this has been resolved.
