### ISSUE TITLE
Addressbook: Cannot set property 'state' of undefined

### ISSUE THREAD

**Issue by fedekunze** [cosmos/voyager#1316]
UI Version: 0.X.X

Description:

```
electron  [Unhandled Promise Rejection] TypeError: Cannot set property 'state' of undefined
              at Addressbook.flagNodeIncompatible (/Users/federico/Projects/voyager/app/src/main/addressbook.js:119:5)
              at _callee9$ (/Users/federico/Projects/voyager/app/src/main/index.js:572:17)
              at tryCatch (/Users/federico/Projects/voyager/node_modules/regenerator-runtime/runtime.js:62:40)
              at Generator.invoke [as _invoke] (/Users/federico/Projects/voyager/node_modules/regenerator-runtime/runtime.js:296:22)
              at Generator.prototype.(anonymous function) [as throw] (/Users/federico/Projects/voyager/node_modules/regenerator-runtime/runtime.js:114:21)
              at step (/Users/federico/Projects/voyager/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
              at /Users/federico/Projects/voyager/node_modules/babel-runtime/helpers/asyncToGenerator.js:30:13
              at <anonymous>
              at process._tickDomainCallback (internal/process/next_tick.js:228:7)

```

**Comment by faboweb** [comment]
Doesn't happen anymore.
