### ISSUE TITLE
TypeError: Cannot read property 'words' of null

### ISSUE THREAD

**Issue by faboweb** [cosmos/voyager#1427]
https://sentry.io/tendermint/cosmos-voyager/issues/718401639/

```
TypeError: Cannot read property 'words' of null
  at Object._doReset (/private/var/folders/9y/jgtj1b7n6mz2_rtg61cvdb140000gn/T/AppTranslocation/610C7176-3827-4A84-AAD2-D00C52F8CC9F/d/Cosmos%20Voyager.app/Contents/Resources/app/dist/renderer.js:107634:33)
  at Object.reset (/private/var/folders/9y/jgtj1b7n6mz2_rtg61cvdb140000gn/T/AppTranslocation/610C7176-3827-4A84-AAD2-D00C52F8CC9F/d/Cosmos%20Voyager.app/Contents/Resources/app/dist/renderer.js:7434:19)
  at Object.reset (/private/var/folders/9y/jgtj1b7n6mz2_rtg61cvdb140000gn/T/AppTranslocation/610C7176-3827-4A84-AAD2-D00C52F8CC9F/d/Cosmos%20Voyager.app/Contents/Resources/app/dist/renderer.js:7772:27)
  at Object.init (/private/var/folders/9y/jgtj1b7n6mz2_rtg61cvdb140000gn/T/AppTranslocation/610C7176-3827-4A84-AAD2-D00C52F8CC9F/d/Cosmos%20Voyager.app/Contents/Resources/app/dist/renderer.js:7419:19)
  at Object.subtype.init (/private/var/folders/9y/jgtj1b7n6mz2_rtg61cvdb140000gn/T/AppTranslocation/610C7176-3827-4A84-AAD2-D00C52F8CC9F/d/Cosmos%20Voyager.app/Contents/Resources/app/dist/renderer.js:6194:46)
...
(9 additional frame(s) were not displayed)
```

**Comment by NodeGuy** [comment]
It would be nice if we had source mapping so that the line numbers in the stack trace were meaningful.

**Comment by faboweb** [comment]
Good idea. Can you create an issue suggesting this?

**Comment by NodeGuy** [comment]
Done: https://github.com/cosmos/voyager/issues/1451
