### ISSUE TITLE
TypeError: _vm.updateDelegates is not a function

### ISSUE THREAD

**Issue by faboweb** [cosmos/voyager#1428]
https://sentry.io/tendermint/cosmos-voyager/issues/715998523/

```
TypeError: _vm.updateDelegates is not a function
  at click (/C:/Users/Administrator/Desktop/Cosmos_Voyager-v0.10.6-Windows/resources/app/dist/renderer.js:130443:580)
  at invoker (/C:/Users/Administrator/Desktop/Cosmos_Voyager-v0.10.6-Windows/resources/app/dist/renderer.js:41954:18)
  at HTMLAnchorElement.fn._withTask.fn._withTask (/C:/Users/Administrator/Desktop/Cosmos_Voyager-v0.10.6-Windows/resources/app/dist/renderer.js:41753:18)
  at HTMLAnchorElement.wrapped (/C:/Users/Administrator/Desktop/Cosmos_Voyager-v0.10.6-Windows/resources/app/dist/renderer.js:90185:21)
```

**Comment by faboweb** [comment]
handled in #1450
