### ISSUE TITLE
TypeError: Cannot read property 'address' of undefined

### ISSUE THREAD

**Issue by faboweb** [cosmos/voyager#1439]
https://sentry.io/tendermint/cosmos-voyager/issues/720197106/

```
TypeError: Cannot read property 'address' of undefined
  at Store._callee$ (/C:/Users/hideki/.cosmos-voyager/resources/app/dist/renderer.js:93719:51)
  at tryCatch (/C:/Users/hideki/.cosmos-voyager/resources/app/dist/renderer.js:69756:40)
  at GeneratorFunctionPrototype.invoke [as _invoke] (/C:/Users/hideki/.cosmos-voyager/resources/app/dist/renderer.js:70009:22)
  at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/C:/Users/hideki/.cosmos-voyager/resources/app/dist/renderer.js:69789:21)
  at step (/C:/Users/hideki/.cosmos-voyager/resources/app/dist/renderer.js:6310:30)
...
(22 additional frame(s) were not displayed)
```

**Comment by NodeGuy** [comment]
Closing because this is a cascading error after https://github.com/cosmos/voyager/issues/1440.
