### ISSUE TITLE
TypeError: Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by faboweb** [cosmos/voyager#1628]
https://sentry.io/tendermint/cosmos-voyager/issues/773149452/?referrer=github_plugin

```
TypeError: Cannot read property 'id' of undefined
  at Store.addToCart (/private/var/folders/kn/6djg7f2932353fwm44_0cxjc0000gn/T/AppTranslocation/D0DE78EF-BAB8-4ED5-8A69-4DA37485BB4F/d/Cosmos%20Voyager.app/Contents/Resources/app/dist/renderer.js:111984:24)
  at wrappedMutationHandler (/private/var/folders/kn/6djg7f2932353fwm44_0cxjc0000gn/T/AppTranslocation/D0DE78EF-BAB8-4ED5-8A69-4DA37485BB4F/d/Cosmos%20Voyager.app/Contents/Resources/app/dist/renderer.js:5868:13)
  at commitIterator (/private/var/folders/kn/6djg7f2932353fwm44_0cxjc0000gn/T/AppTranslocation/D0DE78EF-BAB8-4ED5-8A69-4DA37485BB4F/d/Cosmos%20Voyager.app/Contents/Resources/app/dist/renderer.js:5561:7)
  at Array.forEach (<anonymous>)
  at None (/private/var/folders/kn/6djg7f2932353fwm44_0cxjc0000gn/T/AppTranslocation/D0DE78EF-BAB8-4ED5-8A69-4DA37485BB4F/d/Cosmos%20Voyager.app/Contents/Resources/app/dist/renderer.js:5560:11)
...
(12 additional frame(s) were not displayed)
```

**Comment by faboweb** [comment]
`addToCart` is actual used and removing it produces side effects. needs to be investigated.

**Comment by faboweb** [comment]
Deprioritized because it only happened once.
