### ISSUE TITLE
running a local-testnet requires internet

### ISSUE THREAD

**Issue by jbibla** [cosmos/voyager#1853]
running `yarn start local-testnet` should work without an internet connection but currently it does not. here is the error:

```
$ /Users/jordan/voyager/builds/Gaia/darwin_amd64/gaiad tendermint show-node-id --home /Users/jordan/voyager/builds/testnets/local-testnet/node_home_1
$ mkdir -p /Users/jordan/voyager/builds/testnets/local-testnet/node_home_1/config && /Users/jordan/voyager/builds/Gaia/darwin_amd64/gaiad version > /Users/jordan/voyager/builds/testnets/local-testnet/node_home_1/config/gaiaversion.txt
$ /Users/jordan/voyager/builds/Gaia/darwin_amd64/gaiacli keys add main-account --home /Users/jordan/voyager/builds/testnets/local-testnet/cli_home_1 -o json
{"name":"main-account","type":"local","address":"cosmos18mpdtgsnskzmyf6t76j22xe7exfljs49ugn2mk","pub_key":"cosmospub1addwnpepqfuuq50fwtp6cnme0eyssyhy96vrsaqf6wkq0y9nszhrrp993u5zywqrdzy","seed":"erode always country soap draw then vicious arctic truck crucial human account ugly capable endorse crime web million silly trouble raven accident execute virtual"}
Adding tokens to genesis at /Users/jordan/voyager/builds/testnets/local-testnet/node_home_1/config/genesis.json for address cosmos18mpdtgsnskzmyf6t76j22xe7exfljs49ugn2mk
$ /Users/jordan/voyager/builds/Gaia/darwin_amd64/gaiad gentx --name main-account --home /Users/jordan/voyager/builds/testnets/local-testnet/node_home_1 --home-client /Users/jordan/voyager/builds/testnets/local-testnet/cli_home_1
ERROR: are you connected to the network?
$ /Users/jordan/voyager/builds/Gaia/darwin_amd64/gaiad collect-gentxs --home /Users/jordan/voyager/builds/testnets/local-testnet/node_home_1
Starting the application failed { Error: Command failed: /Users/jordan/voyager/builds/Gaia/darwin_amd64/gaiad collect-gentxs --home /Users/jordan/voyager/builds/testnets/local-testnet/node_home_1
ERROR: open /Users/jordan/voyager/builds/testnets/local-testnet/node_home_1/config/gentx: no such file or directory

    at ChildProcess.exithandler (child_process.js:289:12)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
  killed: false,
  code: 1,
  signal: null,
  cmd:
   '/Users/jordan/voyager/builds/Gaia/darwin_amd64/gaiad collect-gentxs --home /Users/jordan/voyager/builds/testnets/local-testnet/node_home_1',
  stdout: '',
  stderr:
   'ERROR: open /Users/jordan/voyager/builds/testnets/local-testnet/node_home_1/config/gentx: no such file or directory\n' }
✨  Done in 1.13s.
```

**Comment by faboweb** [comment]
This comes from the SDK: https://github.com/cosmos/cosmos-sdk/issues/3424
