### ISSUE TITLE
Fix README: crash on missing ~/.cosmos-voyager-dev/local/gaiaversion.txt

### ISSUE THREAD

**Issue by NodeGuy** [cosmos/voyager#510]
### Version

0.4.3

### Description

I followed the directions on a fresh install to run the UI on a local node with chain_id=local:

`$ yarn run testnet local`

It crashed with:

```
electron  [Unhandled Promise Rejection] { Error: ENOENT: no such file or directory, open '/Users/david/.cosmos-voyager-dev/local/gaiaversion.txt'
              at Object.fs.openSync (fs.js:652:18)
              at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:172:20)
              at Object.fs.readFileSync (fs.js:553:33)
              at Object.fs.readFileSync (ELECTRON_ASAR.js:508:29)
              at _callee9$ (/Users/david/Documents/Tendermint/voyager/app/src/main/index.js:479:32)
              at tryCatch (/Users/david/Documents/Tendermint/voyager/node_modules/regenerator-runtime/runtime.js:62:40)
              at Generator.invoke [as _invoke] (/Users/david/Documents/Tendermint/voyager/node_modules/regenerator-runtime/runtime.js:296:22)
              at Generator.prototype.(anonymous function) [as next] (/Users/david/Documents/Tendermint/voyager/node_modules/regenerator-runtime/runtime.js:114:21)
              at step (/Users/david/Documents/Tendermint/voyager/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
              at /Users/david/Documents/Tendermint/voyager/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
              at <anonymous>
              at process._tickDomainCallback (internal/process/next_tick.js:228:7)
            errno: -2,
            code: 'ENOENT',
            syscall: 'open',
            path: '/Users/david/.cosmos-voyager-dev/local/gaiaversion.txt' }
```

### Log

[main.log](https://github.com/cosmos/voyager/files/1771822/main.log)

**Comment by mappum** [comment]
Hey @NodeGuy, welcome to the team!

We haven't been using the local mode very often, so it looks like one of our recent changes broke it. We usually use `yarn run testnet gaia-2`, although some of the `gaia-2` nodes are currently down so not everything will work, but you can at least see what's there.

**Comment by NodeGuy** [comment]
Thank you.

I'm going to try to document here the steps necessary to run on a local node.

1. Install `basecli` somehow.
1. basecli keys new mykey
1. gaia node init
1. gaia node start
1. COSMOS_NODE=localhost
1. yarn testnet

**Comment by faboweb** [comment]
You don't need `basecli`. `gaia` is a child of `basecli` (the SDK example).
`gaia keys new mykey` also works. This should be changed in Gaia.
The rest looks good. 👍  :)

**Comment by faboweb** [comment]
I removed the information about `yarn testnet local` for now  in #567 as the local node would not produce blocks. A developer can always run his own node, but the documentation for this should be in the SDK repo. 
I suggest we think about adding this feature again when SDK2 is stable. Until then, I suggest we remove code related to `yarn testnet local`.

**Comment by NodeGuy** [comment]
Sounds good to me.
