### ISSUE TITLE
Docker error when I try to build

### ISSUE THREAD

**Issue by nylira** [cosmos/voyager#725]
### Version

0.6.0

### Description

Am I using this command incorrectly?

```
pz@mbp ~/P/cosmos-ui> yarn build --platform=darwin --commit=4a0e323  --sdk-commit=20abeb
3d --network=gaia-5001
yarn run v1.6.0
$ node tasks/build --platform=darwin --commit=4a0e323 --sdk-commit=20abeb3d --network=gaia-5001
docker build       --build-arg SDK_COMMIT=20abeb3d       --tag cosmos/voyager-builder .
Sending build context to Docker daemon  15.87kB
Step 1/38 : FROM golang:1.10.1
 ---> 1af690c44028
Step 2/38 : RUN mkdir release
 ---> Using cache
 ---> 54b9721819e0
Step 3/38 : RUN cd release   && wget https://github.com/golang/dep/releases/download/v0.4.1/dep-linux-amd64
 ---> Using cache
 ---> 75a633b9d317
Step 4/38 : RUN curl --location   https://github.com/golang/dep/releases/download/v0.4.1/dep-linux-amd64.sha256   | sha256sum --check
 ---> Using cache
 ---> 8f63aa7e05bc
Step 5/38 : RUN chmod +x release/dep-linux-amd64
 ---> Using cache
 ---> eb46df58c267
Step 6/38 : RUN mv release/dep-linux-amd64 $GOPATH/bin/dep
 ---> Using cache
 ---> 588f30c612fa
Step 7/38 : RUN cd /   && git clone --bare https://github.com/cosmos/cosmos-sdk
 ---> Using cache
 ---> 271e85e29d12
Step 8/38 : ARG SDK_COMMIT
 ---> Using cache
 ---> 2b073489780f
Step 9/38 : ENV GOOS=linux
 ---> Using cache
 ---> 54079bb3d39f
Step 10/38 : ENV GOPATH=/go/$GOOS
 ---> Using cache
 ---> 45e483c57ead
Step 11/38 : RUN mkdir --parents $GOPATH/src/github.com/cosmos
 ---> Using cache
 ---> 14ac856dfdf8
Step 12/38 : RUN git --git-dir=/cosmos-sdk.git worktree add   $GOPATH/src/github.com/cosmos/cosmos-sdk $SDK_COMMIT
 ---> Using cache
 ---> 8531d43a6d87
Step 13/38 : WORKDIR $GOPATH/src/github.com/cosmos/cosmos-sdk
 ---> Using cache
 ---> 1649af226edd
Step 14/38 : RUN make get_vendor_deps
 ---> Using cache
 ---> 1e7919cf01d6
Step 15/38 : RUN make install
 ---> Using cache
 ---> 35b380cc6c74
Step 16/38 : ENV GOOS=darwin
 ---> Using cache
 ---> c2e2473b3c4a
Step 17/38 : ENV GOPATH=/go/$GOOS
 ---> Using cache
 ---> f676b76a9161
Step 18/38 : RUN mkdir --parents $GOPATH/src/github.com/cosmos
 ---> Using cache
 ---> a220068c6b52
Step 19/38 : RUN git --git-dir=/cosmos-sdk.git worktree add   $GOPATH/src/github.com/cosmos/cosmos-sdk $SDK_COMMIT
 ---> Using cache
 ---> 896a1761f0f0
Step 20/38 : WORKDIR $GOPATH/src/github.com/cosmos/cosmos-sdk
 ---> Using cache
 ---> 47e771036e99
Step 21/38 : RUN make get_vendor_deps
 ---> Using cache
 ---> 16e8cf9bf439
Step 22/38 : RUN make install
 ---> Using cache
 ---> cbdf272716f4
Step 23/38 : ENV GOOS=windows
 ---> Using cache
 ---> 7ed8454f6f9a
Step 24/38 : ENV GOPATH=/go/$GOOS
 ---> Using cache
 ---> cab58d4e30ef
Step 25/38 : RUN mkdir --parents $GOPATH/src/github.com/cosmos
 ---> Using cache
 ---> 70e99238aab4
Step 26/38 : RUN git --git-dir=/cosmos-sdk.git worktree add   $GOPATH/src/github.com/cosmos/cosmos-sdk $SDK_COMMIT
 ---> Using cache
 ---> 723e02134da9
Step 27/38 : WORKDIR $GOPATH/src/github.com/cosmos/cosmos-sdk
 ---> Using cache
 ---> 0f30a180b720
Step 28/38 : RUN make get_vendor_deps
 ---> Using cache
 ---> ae33b5a68854
Step 29/38 : RUN make install
 ---> Using cache
 ---> 561b7cda3204
Step 30/38 : FROM node:9.11.1
 ---> d42348c94e97
Step 31/38 : RUN dpkg --add-architecture i386   && apt-get update   && apt-get install --yes   wine   wine32   libwine
 ---> Using cache
 ---> 73d5ad01513c
Step 32/38 : COPY --from=0 /go/linux/bin /go/linux/bin
 ---> Using cache
 ---> 83c76a62d6ad
Step 33/38 : COPY --from=0 /go/darwin/bin/darwin_amd64 /go/darwin/bin
 ---> Using cache
 ---> 12fdf7f6b204
Step 34/38 : COPY --from=0 /go/windows/bin/windows_amd64 /go/win32/bin
 ---> Using cache
 ---> 5dbf1ff70a33
Step 35/38 : RUN mkdir --parents /usr/src/app
 ---> Using cache
 ---> 81537ac5cf3b
Step 36/38 : WORKDIR /usr/src/app
 ---> Using cache
 ---> 4bbbc0dd94ea
Step 37/38 : COPY entrypoint.sh /
 ---> Using cache
 ---> 397d5e812732
Step 38/38 : ENTRYPOINT [ "/entrypoint.sh" ]
 ---> Using cache
 ---> fc742a4565ed
Successfully built fc742a4565ed
Successfully tagged cosmos/voyager-builder:latest
docker run       --interactive       --mount type=bind,readonly,source=/Users/pz/Projects/cosmos-ui/.git,target=/mnt/.git       --mount type=bind,readonly,source=/Users/pz/Projects/cosmos-ui/gaia-5001,target=/mnt/network       --mount type=bind,source=/Users/pz/Projects/cosmos-ui/builds,target=/mnt/builds       --rm       cosmos/voyager-builder "4a0e323" --skip-pack=false --platform=darwin --commit=4a0e323 --sdk-commit=20abeb3d --network=gaia-5001

docker: Error response from daemon: invalid mount config for type "bind": bind source path does not exist.
See 'docker run --help'.
child_process.js:615
    throw err;
    ^

Error: Command failed: docker run       --interactive       --mount type=bind,readonly,source=/Users/pz/Projects/cosmos-ui/.git,target=/mnt/.git       --mount type=bind,readonly,source=/Users/pz/Projects/cosmos-ui/gaia-5001,target=/mnt/network       --mount type=bind,source=/Users/pz/Projects/cosmos-ui/builds,target=/mnt/builds       --rm       cosmos/voyager-builder "4a0e323" --skip-pack=false --platform=darwin --commit=4a0e323 --sdk-commit=20abeb3d --network=gaia-5001

    at checkExecSyncError (child_process.js:575:11)
    at Object.execSync (child_process.js:612:13)
    at execSync (/Users/pz/Projects/cosmos-ui/tasks/build/index.js:14:16)
    at options (/Users/pz/Projects/cosmos-ui/tasks/build/index.js:48:3)
    at cli (/Users/pz/Projects/cosmos-ui/node_modules/@nodeguy/cli/lib/index.js:19:24)
    at Object.<anonymous> (/Users/pz/Projects/cosmos-ui/tasks/build/index.js:17:1)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by faboweb** [comment]
Did the folder `gaia-5001` exist when you tried this?

**Comment by NodeGuy** [comment]
From the `--help`:

```
--network                  path to the default network to use
```

Perhaps you meant `--network=app/networks/gaia-5001`?

See also [the README](https://github.com/cosmos/voyager#production):

> Here's an example build command:
>
> ```shell
> yarn run build --commit=HEAD --network=app/networks/gaia-5001 --platform=darwin --sdk-commit=35d0e34b2674ad9edf0f074167dd967219dbbe1b
> ```

**Comment by faboweb** [comment]
Is this resolved? @nylira

**Comment by nylira** [comment]
This resolved.
