### ISSUE TITLE
CSS editing in Chrome caused layout trash

### ISSUE THREAD

**Issue by jolesbi** [cosmos/voyager#871]
hey ya'll

on develop b4700eb36af95ca0f5b1b0b205160bb26f6b076b

wondering if you guys have experienced any of the following issues

- source mappings not working
- when editing css in the browser - all css breaks and you have to refresh electron

might have something to do with this:
```
[8032:0622/095513.166795:ERROR:CONSOLE(906)] "TypeError: Cannot read property 'count' of undefined TypeError: Cannot read property 'count' of undefined
              at Function.removeFrameAttribution (chrome-devtools://devtools/bundled/inspector.js:6632:284)
              at Bindings.SASSSourceMapping._sourceMapDetached (chrome-devtools://devtools/bundled/inspector.js:6200:308)
              at SDK.SourceMapManager.dispatchEventToListeners (chrome-devtools://devtools/bundled/inspector.js:472:23)
              at SDK.SourceMapManager.detachSourceMap (chrome-devtools://devtools/bundled/inspector.js:5332:48)
              at SDK.CSSModel._resetStyleSheets (chrome-devtools://devtools/bundled/inspector.js:3719:200)
              at SDK.ResourceTreeModel.dispatchEventToListeners (chrome-devtools://devtools/bundled/inspector.js:472:23)
              at SDK.ResourceTreeModel._frameNavigated (chrome-devtools://devtools/bundled/inspector.js:5136:6)
              at SDK.PageDispatcher.frameNavigated (chrome-devtools://devtools/bundled/inspector.js:5228:47)
              at Protocol.InspectorBackend._DispatcherPrototype.dispatch (chrome-devtools://devtools/bundled/inspector.js:3195:26)
              at SDK.Target._onMessage (chrome-devtools://devtools/bundled/inspector.js:3149:31)", source: chrome-devtools://devtools/bundled/inspector.js (906)
```

**Comment by jolesbi** [comment]
after editing css in electron window:
<img width="1023" alt="screen shot 2018-06-22 at 10 06 00 am" src="https://user-images.githubusercontent.com/6021933/41780850-ebcbf8c8-7603-11e8-929c-97f083f6e7b7.png">

**Comment by faboweb** [comment]
I think those are two different topics, but I have experienced both as well. :(

**Comment by faboweb** [comment]
Happens when a style change causes a reflow.

**Comment by faboweb** [comment]
So the error is, that media queries get stripped after an edit.

A dirty fix seems to be adding another css rule at the bottom of the style tag of a component not being a media query.
