### ISSUE TITLE
Package.json release script doesn't work

### ISSUE THREAD

**Issue by faboweb** [cosmos/voyager#990]
UI Version: 0.7.1

Description:

`yarn release` fails with:

```
internal/modules/cjs/loader.js:550
    throw err;
    ^

Error: Cannot find module '/Users/fabo/Development/voyager/ci/release.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:548:15)
    at Function.Module._load (internal/modules/cjs/loader.js:475:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:695:10)
    at startup (internal/bootstrap/node.js:201:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:516:3)
```

**Comment by faboweb** [comment]
Working now
